version: '3.9'

services:
  mymongo:
    image: mongo
    container_name: ${MONGO_CONTAINER_NAME}
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '${MONGO_EXPRESS_PORT}:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_CONTAINER_NAME}
  
  checker:
    build: ./checker
    depends_on:
      - mymongo

  plot:
    build: ./plot
    depends_on:
      - mymongo
    ports:
      - '${PLOT_EXTERNAL_PORT}:5000'
